### ISSUE TITLE
Question about computing color from sh

### ISSUE THREAD

**Issue by pablodawson** [cvlab-epfl/gaussian-splatting-web#17]
Hey! Thanks for your great work.
Sorry if I'm missing something here, but when computing color, why is the function being evaluated with the camera position, shouldn't be the position of the gaussian?

You end up calculating uniforms.camera_position - uniforms.camera_position = 0 if I'm not mistaken

```
output.color = compute_color_from_sh(uniforms.camera_position, point.sh);

fn compute_color_from_sh(position: vec3<f32>, sh: array<vec3<f32>, 16>) -> vec3<f32> {
let dir = normalize(position - uniforms.camera_position);
```

**Comment by pablodawson** [comment]
By the way I'm attempting to port this to Unity, got all the methods there but it doesn't work yet
https://github.com/pablodawson/GaussianSplattingUnity

**Comment by jatentaki** [comment]
Amazing finding, thanks a lot! I will not push changes right now because it's 15 past midnight and I want to be more level-headed before changing master, but you're right. Not only that, the following division by 0 (since we normalize this 0 vector) was the reason for bugs with 3rd degree spherical harmonics (fixed as well) and is likely to be the factor causing trouble on Windows. You surely have patched it already yourself, but in case see the changes [on this branch](https://github.com/cvlab-epfl/gaussian-splatting-web/tree/fix-compute-sh-args).

**Comment by pablodawson** [comment]
Great to hear!
