### ISSUE TITLE
PLY upload issue

### ISSUE THREAD

**Issue by koktavy** [cvlab-epfl/gaussian-splatting-web#19]
When trying to test the [viewer](https://jatentaki.github.io/assets/gaussianviewer/index.html) I have issues uploading a PLY downloaded from LumaAI (both point cloud and full mesh versions).

The error in the console is
```
packing.ts:157 Uncaught (in promise) PackingError: Error packing value position: Error packing value 0: Expected number, got undefined
    at c.pack (packing.ts:157:27)
    at new l (ply.ts:180:55)
    at r (index.ts:34:31)
    at r.next (<anonymous>)
    at index.ts:7:71
    at new Promise (<anonymous>)
    at index.ts:3:12
```

Is there a recommended way to export the PLY from Blender instead? FBX to PLY maybe?

**Comment by julien-blanchon** [comment]
LumaAI don't do Gaussian Splatting so I don't think this is expected to work. The PLY expected here are gaussian point cloud not classical one.

If you want to make Gaussian Splatting you can try with the original implementation from INRIA https://github.com/graphdeco-inria/gaussian-splatting. If you are looking for a Luma like online service, Polycam do Gaussian Splatting but you might have to buy premium in order to download the PLY ... (you can still get the .ply without premium but I let you figure this out as it's a little bit hacky)

**Comment by jatentaki** [comment]
Oh right, I misunderstood the issue. @julien-blanchon is right that this viewer is not for just any PLY, but specifically the ones created with the INRIA code. Though I agree we could improve the error messages when the format is wrong.
