### ISSUE TITLE
Optimize sorting algorithm

### ISSUE THREAD

**Issue by julien-blanchon** [cvlab-epfl/gaussian-splatting-web#20]
Hi,

This guy (@dakenf on Github) seems to have optimized the sorting algorithm by "changing memory access patter"

https://twitter.com/daken_/status/1702700665510801887

**Comment by jatentaki** [comment]
Thanks a lot, reached out to him :)

**Comment by julien-blanchon** [comment]
Yes me too, I hope at least we can have some insight about what he did ^^

**Comment by dakenf** [comment]
Hi! Yeah, let me clean it up a bit. The main idea is to minimize memory reads and writes using vec4 type
I was also thinking to combine data and indices into one buffer to use mat4x2f type. That will gives about 80fps for the small model on my rtx3090ti. But 
1. still not enough for huge ones, like flowers model from paper authors, since it iterates more than 400 times over all keys/indices. It would give ~20fps max
2. webgpu has a limit of 2gb on buffers so it might simply not fit

So the only way to make it faster is implementing radix sort and i was planning to make a PR after that

**Comment by julien-blanchon** [comment]
Wow you deserve so much love

**Comment by jatentaki** [comment]
Sounds great!

I did not know that reading one vec4f32 is faster than 4x f32, I assumed that a single f32 fetch will fetch the entire block to cache anyway so subsequent reads are faster. Now that I think of it, that's too much of a CPU analogy I guess.

If that's not too much to ask, I think making a PR with the current modification (vec4) would be great, even if bigger and better is already in the making :)

**Comment by dakenf** [comment]
Here you go https://github.com/cvlab-epfl/gaussian-splatting-web/pull/21

**Comment by dakenf** [comment]
> I did not know that reading one vec4f32 is faster than 4x f32, I assumed that a single f32 fetch will fetch the entire block to cache anyway so subsequent reads are faster.

Unfortunately no. And according to FlashAttention paper authors making more computations is much faster than caching to global memory. So they've optimized algorithm by computing values multiple times instead of writing and reading them to global mem

**Comment by jatentaki** [comment]
Integrated in #21
